name: deploy-prod

on:
  push:
    branches:
      - main
jobs:

   deploy:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven 3
        uses: aahmed-se/setup-maven@v3
      
      - name: run package
        run:  mvn  clean package -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}


      - name: mkdir
        run: mkdir artifacts

